version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: users
      MYSQL_DATABASE: users
      MYSQL_USER: users
      MYSQL_PASSWORD: users
  example_2_business_logic:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: example_2_business_logic
    depends_on:
      - db
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
